

use vitech_dev_db;


CREATE SCHEMA vitech_dev_db.BRONZE ;

CREATE SCHEMA vitech_dev_db.SILVER ;

CREATE SCHEMA vitech_dev_db.GOLD ;

---------------
CREATE TABLE vitech_dev_db.BRONZE.CUSTOMER (
    CID INT PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    ADDRS VARCHAR(500),
    STATUS VARCHAR(20),
    CREATTIMT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO vitech_dev_db.BRONZE.CUSTOMER(CID, NAME, EMAIL, ADDRS, STATUS)
VALUES
(111, 'John Smith', 'john.smith@email.com', 'New York, USA', 'ACTIVE'),
(211, 'Mary Johnson', 'mary.johnson@email.com', 'Chicago, USA', 'ACTIVE'),
(311, 'David Brown', 'david.brown@email.com', 'Dallas, USA', 'INACTIVE'),
(411, 'Lisa Wilson', 'lisa.wilson@email.com', 'Seattle, USA', 'ACTIVE'),
(511, 'Michael Davis', 'michael.davis@email.com', 'Boston, USA', 'PENDING');

--------------
CREATE TRANSIENT TABLE vitech_dev_db.BRONZE.CUSTOMER_TRANS (
    CID INT PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    ADDRS VARCHAR(500),
    STATUS VARCHAR(20),
    CREATTIMT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-----TEMP --

CREATE TEMPORARY TABLE vitech_dev_db.BRONZE.CUSTOMER_TEMP (
    CID INT PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    ADDRS VARCHAR(500),
    STATUS VARCHAR(20),
    CREATTIMT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SHOW TABLES;


SELECT * FROM vitech_dev_db.BRONZE.CUSTOMER
  UNION ALL 
SELECT * FROM vitech_dev_db.BRONZE.CUSTOMER_TRANS
  UNION ALL
SELECT * FROM vitech_dev_db.BRONZE.CUSTOMER_TEMP


  --------------------------

  -- Create External Table
CREATE OR REPLACE EXTERNAL TABLE VITECH_DEV_DB.BRONZE.LOAN_PAYMENT_EXT (
    LOAN_ID VARCHAR AS (VALUE:C1::VARCHAR)
)
LOCATION = @VITECH_DEV_DB.STAGES.AWS_EXT_STAGE
 FILE_FORMAT = (TYPE = CSV , SKIP_HEADER= 1) 
PATTERN = '.*Loan_payments_data.*[.]csv';


select * from  VITECH_DEV_DB.BRONZE.LOAN_PAYMENT_EXT;

select * from 
VITECH_DEV_DB.SILVER.CUSTOMER;




------------zero copy ----

 create table VITECH_DEV_DB.silver.CUSTOMER  clone VITECH_DEV_DB.bronze.CUSTOMER;


CREATE OR REPLACE DYNAMIC TABLE VITECH_DEV_DB.silver.CUST_dy
TARGET_LAG = '1 Minutes'
WAREHOUSE = COMPUTE_WH
AS
SELECT 
    CID, 
    NAME, 
    EMAIL, 
    STATUS,
    CREATTIMT
    from VITECH_DEV_DB.bronze.CUSTOMER;





select * from 
VITECH_DEV_DB.bronze.CUSTOMER;

 select * from VITECH_DEV_DB.silver.CUST_dy;


 delete from vitech_dev_db.BRONZE.CUSTOMER;


 
select * from 
VITECH_DEV_DB.bronze.CUSTOMER;



delete from VITECH_DEV_DB.bronze.CUSTOMER
 where status = 'INACTIVE' ;

update  VITECH_DEV_DB.bronze.CUSTOMER
   set status = 'INACTIVE'
   where cid = 111
--------------------------------
CREATE OR REPLACE TASK VITECH_DEV_DB.BRONZE.DELETE_INACTIVE_CUSTOMERS
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
AS
delete from VITECH_DEV_DB.bronze.CUSTOMER
 where status = 'INACTIVE' ;

 show tables;


 ALTER TASK VITECH_DEV_DB.BRONZE.DELETE_INACTIVE_CUSTOMERS RESUME;


 ALTER TASK VITECH_DEV_DB.BRONZE.DELETE_INACTIVE_CUSTOMERS suspend;


show tables;
VITECH_DEV_DB.DEV_DB_COPY2.EMPLOYEES
 delete from VITECH_DEV_DB.DEV_DB_COPY2.DEV_DB_COPY

delete from  VITECH_DEV_DB.DEV_DB_COPY2.DEV_DB_COPY1

 delete from VITECH_DEV_DB.DEV_DB_COPY2.EMPLOYEESVITECH_DEV_DB.DEV_DB_COPY2.ORDERS_STAGE

  delete from VITECH_DEV_DB.DEV_DB_COPY2.ORDERS_STAGE